services:
  concrete-manage-test:
    restart: always
    image: nginx:alpine
    container_name: ${DOCKER_CONTAINER_NAME}
    environment:
      - NGINX_PORT=80
      - ENV1=${ENV1}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./source/conf.d:/etc/nginx/conf.d
      - ./source/dist:/usr/share/nginx/html
      - ./log/:/var/log/nginx/
    networks:
      - proxy

networks:
  proxy:
    external: true
